### ISSUE TITLE
cifar_utils missing

### ISSUE THREAD

**Issue by dionman** [inspire-group/ModelPoisoning#1]
It seems that cifar_utils is missing, giving the following error when trying to train the model with the command written in readme

 File "code/ModelPoisoning/agents.py", line 11, in <module>
    from cifar_utils import cifar_10_model
ImportError: No module named cifar_utils

**Comment by HaiQW** [comment]
I come across the same error "No module named cifar_utils".

**Comment by arjunbhagoji** [comment]
The issue was with an unnecessary import. That has been fixed now.

**Comment by prateek-mittal** [comment]
Great, thanks Arjun!
