### ISSUE TITLE
Many small errors existing in the source code

### ISSUE THREAD

**Issue by HaiQW** [inspire-group/ModelPoisoning#2]
I ran the source code and still met many small errors. These errors are summarized below:
1) from mnist import * ==> from utils.mnist import * 
2 allow_pickle=True should be added to np.load

**Comment by arjunbhagoji** [comment]
Thanks for pointing these out.
1. I have made the edits.
2. Numpy has changed the default option for pickling in numpy.load for versions 1.17 and 1.18, so I've added the pickling now.
