### ISSUE TITLE
experiments on cifar10 dataset

### ISSUE THREAD

**Issue by Abonnen** [inspire-group/ModelPoisoning#3]
The source code contains `cifar_10_model`, but I cannot find the definition, so I made a minor change on source code and did some experiments on cifar10 dataset.
However, the result shows that the malicious agent succeeded in 40 of 40 iterations with high confidence in both `converge` and `dist` strategy. Is that normal ?

**Comment by arjunbhagoji** [comment]
Thanks for your interest in our code. Could you create a pull request with the changes you made to run the cifar model?

In general, I think the attack is quite strong and if you are choosing the malicious agent at every time step, it is expected that the agent would succeed at every iteration. However, I can't say for sure without examining your code and results.
