### ISSUE TITLE
Problem for Multiprocessing

### ISSUE THREAD

**Issue by grasses** [inspire-group/ModelPoisoning#4]
I find error about multiprocessing in my environment, so I change the Process to single thread, but I can't get the similar weights distribution results in your paper. My questions are:
1. What params should I add to get the results of "Alternating minimization with distances constraints" in your paper.
2. I find your params "--mal_strat=converge" in the code is useless, does it true? And how to adjust the params to make malicious agent attack at the convergence of model.
3. Does it have influence for weights distributions if I change it to single thread execution?

**Comment by arjunbhagoji** [comment]
1. I have added that to the README
2. The `mal_strat` parameter chooses which strategy the malicious agent follows. Setting it to 'converge' simply uses the baseline attack. To change when the malicious agent attacks, use the `mal_delay` parameter.
3. Using multiprocessing is a way to speed up the execution. Training each agent serially and then aggregating should not change the results.

Feel free to reopen if there are remaining issues
