### ISSUE TITLE
Can't reproduce the results in paper

### ISSUE THREAD

**Issue by J-BING** [inspire-group/ModelPoisoning#9]
Hi Arjun, I have reproduced the experiment of the alternating minimization attack following the command in README:

```
python dist_train_w_attack.py --dataset=fMNIST --k=10 --C=1.0 --E=5 --T=40 --train --model_num=0 --mal --mal_obj=single --mal_strat=converge_train_alternate_wt_o_dist_self --rho=1e-4 --gar=avg --ls=10 --mal_E=10
```
However, the result shows that "Malicious agent succeeded in 0 of 6 iterations". After checking the source code, I find that during the 6 iterations the global model correctly predicted the malicious data with the label "5".  And the output file for predicting the malicious data is as following:

t,target,target_conf,actual,actual_conf
1,7,0.18352902,5,0.5428532
2,7,0.13259208,5,0.849949
3,7,0.04781367,5,0.9503012
4,7,0.09260346,5,0.9071523
5,7,0.48864973,5,0.51109886
6,7,0.48037982,5,0.5195737

The results are not consistent with the figures in the paper that show the global model misclassifies the malicious data in confidence nearly 1 after 3 iterations. So did I miss something? Why does it happend? Thanks.

**Comment by arjunbhagoji** [comment]
Hi,

I just ran the alternating minimization attack from the README after making some minor changes to the code for compatibility with tfv2 and Python 3. I am able to reproduce the results from the paper and get the following output:

t,target,target_conf,actual,actual_conf
1,7,0.49331033,7,0.49331033
2,7,0.99081635,7,0.99081635
3,7,0.997109,7,0.997109
4,7,0.9847816,7,0.9847816
5,7,0.18902512,5,0.8109748
6,7,0.58639216,7,0.58639216
7,7,0.81649995,7,0.81649995

Perhaps you can try a different random seed (currently set to 777) at https://github.com/inspire-group/ModelPoisoning/blob/5a54f4d7efc6fec0d78a310bb65c03d5c9e6986f/dist_train_w_attack.py#L253?
